services:

  workspace:
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
    working_dir: /var/www/laravel
    volumes:
      - ../:/var/www/laravel
    ports:
      - "${PHP_PORT:-9000}:9000"
      - "${VITE_PORT:-5173}:5173"
    tty: true
    networks:
      - laravel-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: ${NGINX_IMAGE}
    volumes:
      - ../:/var/www/laravel:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${NGINX_PORT_HTTP:-80}:80"
      - "${NGINX_PORT_HTTPS:-433}:443"
    depends_on:
      - workspace
    networks:
      - laravel-network

  memcached:
    image: 'memcached:alpine'
    ports:
      - '${MEMCACHED_PORT:-11211}:11211'
    networks:
      - laravel-network

  mailpit:
    image: ${MAILPIT_IMAGE}
    ports:
      - "${MAILPIT_SMTP_PORT:-1025}:1025" # smtp server
      - "${MAILPIT_DASHBOARD_PORT:-8025}:8025" # web ui
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
